apiVersion: v1
kind: ConfigMap
metadata:
  name: globalowner-adopt
  namespace: {{ include "globalowner.namespace" . }}
data:
  adopt.jsonnet: |-
{{ .Files.Get "adopt.jsonnet" | indent 4}}
  customize.jsonnet: |-
{{ .Files.Get "customize.jsonnet" | indent 4}}