kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "globalowner.name" . }}-adopt
  labels:
    {{ .Values.aggregationLabel }}: "true"
rules:
  ## Adopter
  - apiGroups:
      - globalowner.metacontroller.io
    resources:
      - globalowners
      - globalowners/status
    verbs:
      - create
      - update
      - get
      - list
      - watch
      - patch
