apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | default .Release.Name }}-adopt
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name | default .Release.Name }}-adopt
  template:
    metadata:
      labels:
        app: {{ .Values.name | default .Release.Name }}-adopt
    spec:
      containers:
      - name: controller
        image: python:3.9
        command: ["python", "/hooks/adopt.py"]
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: globalowner-adopt
