apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | default .Release.Name }}-adopt
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.name | default .Release.Name }}-adopt
  ports:
  - port: 80