kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "globalowner.name" . }}-bind
  labels:
    {{ .Values.aggregationLabel }}: "true"
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - create
      - update
      - get
      - list
      - watch
      - patch
      - bind
      - impersonate
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
    verbs:
      - create
      - update
      - get
      - list
      - watch
      - patch
      - escalate
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - create
      - update
      - get
      - list
      - watch
      - patch
      - bind
      - impersonate