kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "globalowner.name" . }}-chain
  labels:
    {{ .Values.aggregationLabel }}: "true"
rules:
  - apiGroups:
      - globalowner.metacontroller.io
    resources:
      - groupowners
    verbs:
      - create
      - update
      - patch