apiVersion: v1
kind: ConfigMap
metadata:
  name: globalowner-chain
  namespace: {{ include "globalowner.namespace" . }}
data:
  chain-ownership.jsonnet: |-
{{ .Files.Get "chain-ownership.jsonnet" | indent 4 }}
