apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "globalowner.name" . }}-chain
  namespace: {{ include "globalowner.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "globalowner.name" . }}-chain
  template:
    metadata:
      labels:
        app: {{ include "globalowner.name" . }}-chain
    spec:
      containers:
      - name: hooks
        image: {{ .Values.image }}
        imagePullPolicy: Always
        workingDir: /hooks
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: globalowner-chain