kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "globalowner.name" . }}
  labels:
    {{ .Values.aggregationLabel }}: "true"
rules:
  ## Default rule set
  - apiGroups:
      - metacontroller.k8s.io
    resources:
      - compositecontrollers
      - controllerrevisions
      - decoratorcontrollers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - "*"
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch