---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: globalowner-controller
spec:
  parentResource:
    apiVersion: globalowner.metacontroller.io/v1alpha1
    resource: globalowners
  childResources:
  - apiVersion: v1
    resource: configmaps
  hooks:
    sync:
      webhook:
        url: http://globalowner-controller.metacontroller/sync
    customize:
      webhook:
        url: http://globalowner-controller.metacontroller/customize