apiVersion: globalowner.metacontroller.io/v1alpha1
kind: GlobalOwner
metadata:
  name: global-owner
spec:
  selector:
    matchExpressions:
    - {key: adopt, operator: Exists}
  childResources:
  - apiVersion: v1
    resource: secrets
    namespace: default
    names:
    - test
  - apiVersion: v1
    resource: configmaps
