---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: globalowner-adopt
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globalowner-adopt
  template:
    metadata:
      labels:
        app: globalowner-adopt
    spec:
      containers:
      - name: hooks
        image: metacontroller/jsonnetd:0.20
        imagePullPolicy: Never
        workingDir: /hooks
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: globalowner-adopt
---
apiVersion: v1
kind: Service
metadata:
  name: globalowner-adopt
  namespace: metacontroller
spec:
  selector:
    app: globalowner-adopt
  ports:
  - port: 80
    targetPort: 8080