kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: globalowner-chain
  labels:
    rbac.metacontroller.k8s.io/aggregate-to-metacontroller: "true"
rules:
  - apiGroups:
      - globalowner.metacontroller.io
    resources:
      - groupowners
    verbs:
      - create
      - update
      - patch