apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: globalowner-chain
spec:
  generateSelector: true
  parentResource:
    apiVersion: globalowner.metacontroller.io/v1alpha1
    resource: globalowners
  childResources:
  - apiVersion: globalowner.metacontroller.io/v1alpha1
    resource: groupowners
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://globalowner-chain/chain-ownership
        timeout: 10s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: globalowner-chain
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globalowner-chain
  template:
    metadata:
      labels:
        app: globalowner-chain
    spec:
      containers:
      - name: hooks
        image: ghcr.io/danil-grigorev/jsonnetd:v0.3.1
        imagePullPolicy: Always
        workingDir: /hooks
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: globalowner-chain
---
apiVersion: v1
kind: Service
metadata:
  name: globalowner-chain
  namespace: metacontroller
spec:
  selector:
    app: globalowner-chain
  ports:
  - port: 80
    targetPort: 8080