resources:
- bootstrapper.yaml
- adopter.yaml
configMapGenerator:
- name: globalowner-adopt
  namespace: metacontroller
  files:
  - adopt.py
- name: globalowner-bootstrap
  namespace: metacontroller
  files:
  - bootstrap-globalowner.jsonnet
