name: release

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  TAG: ${{ github.ref_name }}
  CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  RELEASE_DIR: .cr-release-packages
  REPO: ${{ github.repository }}
  CR_SKIP_EXISTING: true

jobs:
  release:
    name: Create helm release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Package operator chart
        run: RELEASE_TAG=${GITHUB_REF##*/} CHART_PACKAGE_DIR=${RELEASE_DIR} make release-chart

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0